### ISSUE TITLE
No module named 'custom_nodes.Derfuu_ComfyUI_ModdedNodes'

### ISSUE THREAD

**Issue by juh9870** [Derfuu/Derfuu_ComfyUI_ModdedNodes#13]
Nodes do not get added due to module import error
Error log: https://pastebin.com/EMe1sUa3
Comfy UI version: https://github.com/comfyanonymous/ComfyUI/commit/492db2de8db7e082addf131b40adb4a1b7535821

**Comment by TricksyZerg** [comment]
getting the same error

**Comment by Cococyh** [comment]
> Nodes do not get added due to module import error Error log: https://pastebin.com/EMe1sUa3 Comfy UI version: [comfyanonymous/ComfyUI@492db2d](https://github.com/comfyanonymous/ComfyUI/commit/492db2de8db7e082addf131b40adb4a1b7535821)

i meet this error because my filename is wrong with the "./custom_nodes/Derfuu_ComfyUI_ModdedNodes_master", i delate "_master", then everything goes well.

> getting the same error

**Comment by juh9870** [comment]
I don't have `_master` in the name. I have repo placed in `custom_nodes/Derfuu_ComfyUI_ModdedNodes/`

**Comment by Derfuu** [comment]
Should be fixed now. Maybe there was errors with the absolute import paths.

**Comment by BAIS1C** [comment]
> Should be fixed now. Maybe there was errors with the absolute import paths.

im getting the error all installed, from git clone. but

![image](https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes/assets/125931341/4b0b528b-c8db-4e2e-ae67-b0a692f7b4f8)

**Comment by eriicfreez** [comment]
getting the same error
![Screenshot 2024-04-27 234231](https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes/assets/150654897/f2ef2d56-5bd5-4be9-9280-82c39d84c7bd)

**Comment by Derfuu** [comment]
> 
> im getting the error all installed, from git clone. but

> getting the same error
>

Are there any details or logs about what did you do to get this error?

**Comment by eriicfreez** [comment]
> > im getting the error all installed, from git clone. but
> 
> > getting the same error
> 
> Are there any details or logs about what did you do to get this error?

at startup the node loaded 

Import times for custom nodes:
[2024-04-28 00:05]    0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
[2024-04-28 00:05]    0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
[2024-04-28 00:05]    0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
[2024-04-28 00:05]    0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\wlsh_nodes
[2024-04-28 00:05]    0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
[2024-04-28 00:05]    0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\hd_node
[2024-04-28 00:05]    0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
[2024-04-28 00:05]    0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
[2024-04-28 00:05]    0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
[2024-04-28 00:05]    0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
[2024-04-28 00:05]    0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
[2024-04-28 00:05]    0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
[2024-04-28 00:05]    0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
[2024-04-28 00:05]    0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
[2024-04-28 00:05]    0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR
[2024-04-28 00:05]    0.2 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[2024-04-28 00:05]    0.3 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID
[2024-04-28 00:05]    0.3 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-04-28 00:05]    0.8 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui
[2024-04-28 00:05]    0.9 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CCSR
[2024-04-28 00:05]    1.1 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hangover-Moondream
[2024-04-28 00:05]    1.5 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
[2024-04-28 00:05]    1.6 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes
[2024-04-28 00:05]    2.9 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
[2024-04-28 00:05] 


After force the queue prompt 


[2024-04-28 00:05] got prompt
[2024-04-28 00:05] Error handling request
Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\server.py", line 41, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\server.py", line 53, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\server.py", line 468, in post_prompt
    valid = execution.validate_prompt(prompt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 625, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
                                       ~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'class_type'

![Screenshot 2024-04-28 001442](https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes/assets/150654897/95ae6a86-1ddf-4c73-bf1c-11ef8f5714a8)

**Comment by cgwers** [comment]
Here's my, "Me, too."

I did the install in manager with install from git and also tried cloning and manually unzipping the files in-place.

**Comment by prezofpizza** [comment]
Throwing my "me too" in the ring as well.

**Comment by Derfuu** [comment]
Currently, I don't understand what could cause these import errors. As i can see from @eriicfreez [log](https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes/issues/13#issuecomment-2081104216) - is that this error rasies from default ComfyUI package. 
Tried to install them on portable version of ComfyUI through ComfyUI-Manager and it works normally. Same about local version.

All i can suggest for now is:
- Check your python version. Should be 3.10 or later;
- Make sure that even with only these nodes it fails to import/load/execute prompt;
- Update nodes/ComfyUI;
- Re-set nodes in workflow;
- Reinstall custom nodes/ComfyUI;

Maybe one of these steps will help you.

**Comment by duckkg** [comment]
我也遇到了相同的问题

**Comment by duckkg** [comment]
> > > 我从 git clone 得到全部安装的错误。
> > 
> > 
> > > 得到同样的错误
> > 
> > 
> > 是否有任何详细信息或日志说明您做了什么才出现此错误？
> 
> 启动时加载节点
> 
> 自定义节点的导入时间： [2024-04-28 00:05] 0.0 秒：E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py [2024-04-28 00:05] 0.0 秒：E:\ ComfyUI \ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler [2024-04-28 00:05] 0.0 秒： E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere [2024-04-28 00:05] 0.0秒： E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\wlsh_nodes [2024-04-28 00:05] 0.0 秒： E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus [2024-04-28 00:05] 0.0秒： E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\hd_node [2024-04-28 00:05] 0.0 秒： E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver [2024-04-28 00: 05 ] ] 0.0 秒：E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet [2024-04-28 00:05] 0.0 秒：E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNode s [2024- 04- 28 00:05] 0.0 秒：E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts [2024-04-28 00:05] 0.0 秒：E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ ComfyUI- KJNodes [2024-04-28 00:05] 0.0秒：E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rg 三舒适 [2024-04-28 00:05] 0.0秒：E:\ComfyUI\ComfyUI_windows_portable \ComfyUI\ custom_nodes\ComfyUI_essentials [2024-04-28 00:05] 0.0 秒： E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes [2024-04-28 00:05] 0.0 秒： E:\ComfyUI\Comf yUI_windows_端口能够\ComfyUI\ custom_nodes\ComfyUI-SUPIR [2024-04-28 00:05] 0.2秒：E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack [2024-04-28 00:05] 0.3秒：E:\ ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID [2024-04-28 00:05] 0.3秒：E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager [2024-04-28 00:05] 0.8秒：E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui [2024-04-28 00:05] 0.9秒：E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CCSR [2024-04-28 00:05] 1.1秒：E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hangover-Moondream [2024-04-28 00:05] 1.5秒：E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node -suite-comfyui [2024-04-28 00:05] 1.6秒：E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes [2024-04-28 00:05] 2.9秒：E:\ComfyUI \ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools [2024-04-28 00:05]
> 
> 强制队列提示后
> 
> [2024-04-28 00:05] 得到提示 [2024-04-28 00:05] 处理请求 回溯时出错（最近一次调用最后一次）： 文件“E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site- packages\ aiohttp\web_protocol.py"，第452行，在 _handle_request resp = wait request_handler(request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^ 文件中“E：\ ComfyUI \ ComfyUI_windows_portable \ python_embeded \ Lib \ site-packages \ aiohttp \ web_app.py”，第543行，_句柄中 =等待处理程序（请求） ^^^^^^^ ^^^^^^^^^ ^^^^^^^^ 文件“E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py”，第114行，隐式 返回等待处理程序（请求） ^^^^^^^^^ ^^^^^^^^^^^^^^^^ 文件“E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\server.py”，第41行，cache_control 响应中： web.Response = wait handler(request) ^^^^ ^^^^^^^^^^^^^^^^^^^^ 文件“E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\server.py”，第 53 条行，在 cors_middleware 响应 = 等待处理程序(请求) ^^^^ ^^^^^^^^^^^^^^^^^^^^ 文件“E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\server.py” ，第468行，在post_prompt valid =execution.validate_prompt(prompt) ^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 文件“E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py”，第625行，位于validate_prompt class_ =nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']] ~~~~~~~~~^^^ ^^^^^^^^^^^^^ KeyError：'class_type'
> 
> ![截图 2024-04-28 001442](https://private-user-images.githubusercontent.com/150654897/326194819-95ae6a86-1ddf-4c73-bf1c-11ef8f5714a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NzA4MDQsIm5iZiI6MTcxNDY3MDUwNCwicGF0aCI6Ii8xNTA2NTQ4OTcvMzI2MTk0ODE5LTk1YWU2YTg2LTFkZGYtNGM3My1iZjFjLTExZWY4ZjU3MTRhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQxNzIxNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGM2MWM4YzRkZjhlN2NlNjM3ZTVkYTFiMDJkMDU5ZDcyZDBiZmVhY2FlODMzZWQ3NTY5MzA2Zjk3YmNlYjhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QYGPpeDIzxTrw6c8pKAkE5dimMc6uu1ck29L8HYDAFU)

问题解决了吗

**Comment by BAIS1C** [comment]
I do not have the problem after latest update, thank you. There are some old BoXES that do not load. but as derfuu is now visible there, I can substitute that text box with a new derfuu text box and everything works.

**Comment by Mohsyn** [comment]
> I do not have the problem after latest update, thank you. There are some old BoXES that do not load. but as derfuu is now visible there, I can substitute that text box with a new derfuu text box and everything works.

That is exactly the problem a lot of nodes do not load and become red boxes.
It seems there is no solution at the moment. I thought this is a new issue. it is 8 months old

**Comment by fabiotgolo** [comment]
I got the same problem. I think because I'm on Mac.

**Comment by Metatronovich** [comment]
Same problem, windows 11.

**Comment by yxhaaaa** [comment]
same error,windows11

**Comment by ioritree** [comment]
Same problem, windows 11.

**Comment by ChicoSir** [comment]
同样的问题，Windows 11。

**Comment by ChicoSir** [comment]
<img width="966" alt="截图_2024-06-07_16-40-07" src="https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes/assets/44128292/e21df33b-9e97-408c-bfde-fb2b385496df">
