### ISSUE TITLE
[BUG/ERROR] IMPORT failed - TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by cihangoksu** [Derfuu/Derfuu_ComfyUI_ModdedNodes#26]
**Describe the bug**
After I tried installing derfuu via comfyui manager, comfyui started shooting following IMPORT FAILED error
with "TypeError: unsupported operand type(s) for |: 'type' and 'type'". Any idea to fix please?

**Full Log is below**
## ComfyUI-Manager: installing dependencies done.
[2024-05-04 13:43] ** ComfyUI startup time: 2024-05-04 13:43:44.655452
[2024-05-04 13:43] ** Platform: Windows
[2024-05-04 13:43] ** Python version: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
[2024-05-04 13:43] ** Python executable: C:\ProgramData\Anaconda3\python.exe
[2024-05-04 13:43] ** Log path: C:\Users\cgksu\Dropbox\Business\Nekodu_Technology\Nekodu_Technology_Common\Users\cgoksu\Miscellaneous\ComfyUI\comfyui.log
[2024-05-04 13:43] 
Prestartup times for custom nodes:
[2024-05-04 13:43]    0.2 seconds: C:\Users\cgksu\Dropbox\Business\Nekodu_Technology\Nekodu_Technology_Common\Users\cgoksu\Miscellaneous\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-05-04 13:43] 
Total VRAM 4096 MB, total RAM 16143 MB
[2024-05-04 13:43] Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --normalvram
[2024-05-04 13:43] Set vram state to: LOW_VRAM
[2024-05-04 13:43] Device: cuda:0 NVIDIA GeForce GTX 1650 Ti with Max-Q Design : 
[2024-05-04 13:43] VAE dtype: torch.float32
[2024-05-04 13:43] Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
[2024-05-04 13:43] ### Loading: ComfyUI-Manager (V2.24.1)
[2024-05-04 13:43] ### ComfyUI Revision: 2134 [d64e2174] | Released on '2024-04-17'
[2024-05-04 13:43] Traceback (most recent call last):
  File "C:\Users\cgksu\Dropbox\Business\Nekodu_Technology\Nekodu_Technology_Common\Users\cgoksu\Miscellaneous\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\cgksu\Dropbox\Business\Nekodu_Technology\Nekodu_Technology_Common\Users\cgoksu\Miscellaneous\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes\__init__.py", line 8, in <module>
    from .pyscripts.Nodes.Custom import Types as TypeNodes
  File "C:\Users\cgksu\Dropbox\Business\Nekodu_Technology\Nekodu_Technology_Common\Users\cgoksu\Miscellaneous\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes\pyscripts\Nodes\Custom\Types.py", line 1, in <module>
    from ...components.fields import Field
  File "C:\Users\cgksu\Dropbox\Business\Nekodu_Technology\Nekodu_Technology_Common\Users\cgoksu\Miscellaneous\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes\pyscripts\components\fields.py", line 12, in <module>
    class Field:
  File "C:\Users\cgksu\Dropbox\Business\Nekodu_Technology\Nekodu_Technology_Common\Users\cgoksu\Miscellaneous\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes\pyscripts\components\fields.py", line 14, in Field
    def field(field: str | list, data: dict = None) -> tuple[str | list, dict] | tuple[str | list]:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

[2024-05-04 13:43] Cannot import C:\Users\cgksu\Dropbox\Business\Nekodu_Technology\Nekodu_Technology_Common\Users\cgoksu\Miscellaneous\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes module for custom nodes: unsupported operand type(s) for |: 'type' and 'type'
[2024-05-04 13:43] 
Import times for custom nodes:
[2024-05-04 13:43]    0.0 seconds: C:\Users\cgksu\Dropbox\Business\Nekodu_Technology\Nekodu_Technology_Common\Users\cgoksu\Miscellaneous\ComfyUI\custom_nodes\websocket_image_save.py
[2024-05-04 13:43]    0.0 seconds (IMPORT FAILED): C:\Users\cgksu\Dropbox\Business\Nekodu_Technology\Nekodu_Technology_Common\Users\cgoksu\Miscellaneous\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
[2024-05-04 13:43]    0.2 seconds: C:\Users\cgksu\Dropbox\Business\Nekodu_Technology\Nekodu_Technology_Common\Users\cgoksu\Miscellaneous\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-05-04 13:43] 
[2024-05-04 13:43] Starting server

[2024-05-04 13:43] To see the GUI go to: http://127.0.0.1:8188
[2024-05-04 13:43] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[2024-05-04 13:43] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[2024-05-04 13:43] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[2024-05-04 13:43] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

**Comment by Derfuu** [comment]
looks like you got python version lower than 3.10, Am I right? If so - please update python to this version or newer.

**Comment by cihangoksu** [comment]
Yeppieee upgrading to 3.10 resolved the issue (torch update needed)! Tyu very much :-)
